[2024-08-10 10:41:11,391] 19 root - INFO - logging has started
[2024-08-10 10:41:58,212] 19 root - INFO - logging has started
[2024-08-10 10:43:28,061] 19 root - INFO - Exception Error occured in python script name [F:\python\ML_DL_project\MNIST_DIGIT_RECOGNITION\src\exception.py] line number [26] error message [division by zero]
